#!/bin/bash

wget -q --spider http://google.com

if [ $? -eq 0 ]
then
  count=$(checkupdates | wc -l)

  if [[ "$count" == "0" ]]
  then
    echo "System up to date!"
  else
    echo "There are [$count] updates!"
  fi
else
  echo "Network problem..."
fi
