#!/bin/bash

wget -q --spider http://google.com

if [ $? -eq 0 ]
then
  count=$(checkupdates | wc -l)

  if [[ "$count" == "0" ]]
  then
    echo "System up to date!"
  else
    notify-send -t 2000 "There are [$count] updates!"
    echo "There are [$count] updates!"
  fi
else
  notify-send -t 2000 "Network not connected."
  echo "Network problem..."
fi
